USE [master]
GO

/****** Object:  Database [BANCA_DE_JORNAL]    Script Date: 29/05/2019 00:44:55 ******/
CREATE DATABASE [BANCA_DE_JORNAL]
GO

USE [BANCA_DE_JORNAL]
GO

/****** Object:  Table [dbo].[CATALOGO]    Script Date: 29/05/2019 00:44:55 ******/
CREATE TABLE [dbo].[CATALOGO](
	[IDPRODUTO] [int] IDENTITY(1,1) NOT NULL,
	[DESC_PRODUTO] [varchar](50) NULL,
	[VALOR_PRODUTO] [decimal](10, 2) NULL,
	[IDFORNECEDOR] [int] NULL,
	[QUANTIDADE_ESTOQUE] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[IDPRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[COMPRA]    Script Date: 29/05/2019 00:44:57 ******/
CREATE TABLE [dbo].[COMPRA](
	[IDFORNECEDOR] [int] NULL,
	[IDCOMPRA] [int] IDENTITY(1,1) NOT NULL,
	[DATA_VENDA] [datetime] NULL,
	[PRECO_VENDA] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDCOMPRA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[DEVOLUCAO]    Script Date: 29/05/2019 00:44:57 ******/
CREATE TABLE [dbo].[DEVOLUCAO](
	[IDFORNECEDOR] [int] NULL,
	[IDDEVOLUCAO] [int] IDENTITY(1,1) NOT NULL,
	[DATA_DEVOLUCAO] [datetime] NULL,
	[PRECO_DEVOLUCAO] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDDEVOLUCAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[FORNECEDOR]    Script Date: 29/05/2019 00:44:57 ******/
CREATE TABLE [dbo].[FORNECEDOR](
	[IDFORNECEDOR] [int] IDENTITY(1,1) NOT NULL,
	[RAZAO_SOCIAL] [varchar](50) NULL,
	[CNPJ] [varchar](14) NULL,
	[ENDERECO] [varchar](50) NULL,
	[TELEFONE] [varchar](11) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDFORNECEDOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[PRODUTO_COMPRA]    Script Date: 29/05/2019 00:44:57 ******/
CREATE TABLE [dbo].[PRODUTO_COMPRA](
	[IDPRODUTO] [int] NULL,
	[IDCOMPRA] [int] NULL,
	[QUANTIDADE_COMPRA] [int] NULL,
	[PRECO_UNITARIO] [decimal](10, 2) NULL
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[PRODUTO_DEVOLUCAO]    Script Date: 29/05/2019 00:44:57 ******/
CREATE TABLE [dbo].[PRODUTO_DEVOLUCAO](
	[IDPRODUTO] [int] NULL,
	[IDDEVOLUCAO] [int] NULL,
	[QUANTIDADE_DEVOLUCAO] [int] NULL,
	[PRECO_UNITARIO] [decimal](10, 2) NULL
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[PRODUTO_VENDA]    Script Date: 29/05/2019 00:44:57 ******/
CREATE TABLE [dbo].[PRODUTO_VENDA](
	[IDPRODUTO] [int] NULL,
	[IDVENDA] [int] NULL,
	[QUANTIDADE_VENDA] [int] NULL,
	[PRECO_UNITARIO] [decimal](10, 2) NULL
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[USUARIO]    Script Date: 29/05/2019 00:44:57 ******/
CREATE TABLE [dbo].[USUARIO](
	[IDUSUARIO] [int] IDENTITY(1,1) NOT NULL,
	[NOME_USUARIO] [varchar](50) NULL,
	[SENHA] [varchar](50) NULL,
	[ACESSO] [char](1) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDUSUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[VENDA]    Script Date: 29/05/2019 00:44:57 ******/
CREATE TABLE [dbo].[VENDA](
	[IDVENDA] [int] IDENTITY(1,1) NOT NULL,
	[PRECO_VENDA] [decimal](10, 2) NULL,
	[DATA_VENDA] [datetime] NULL,
	[TP_PAGAMENTO] [char](1) NULL,
PRIMARY KEY CLUSTERED 
(
	[IDVENDA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CATALOGO]  WITH CHECK ADD  CONSTRAINT [fk_FORNECEDORCATALOGO] FOREIGN KEY([IDFORNECEDOR])
REFERENCES [dbo].[FORNECEDOR] ([IDFORNECEDOR])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CATALOGO] CHECK CONSTRAINT [fk_FORNECEDORCATALOGO]
GO
ALTER TABLE [dbo].[COMPRA]  WITH CHECK ADD  CONSTRAINT [fk_COMPRAFORNECEDOR] FOREIGN KEY([IDFORNECEDOR])
REFERENCES [dbo].[FORNECEDOR] ([IDFORNECEDOR])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[COMPRA] CHECK CONSTRAINT [fk_COMPRAFORNECEDOR]
GO
ALTER TABLE [dbo].[DEVOLUCAO]  WITH CHECK ADD  CONSTRAINT [fk_FORNECEDORDEVOLUCAO] FOREIGN KEY([IDFORNECEDOR])
REFERENCES [dbo].[FORNECEDOR] ([IDFORNECEDOR])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DEVOLUCAO] CHECK CONSTRAINT [fk_FORNECEDORDEVOLUCAO]
GO
ALTER TABLE [dbo].[PRODUTO_COMPRA]  WITH CHECK ADD  CONSTRAINT [fk_PRODUTOCOMPRA] FOREIGN KEY([IDCOMPRA])
REFERENCES [dbo].[COMPRA] ([IDCOMPRA])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRODUTO_COMPRA] CHECK CONSTRAINT [fk_PRODUTOCOMPRA]
GO
ALTER TABLE [dbo].[PRODUTO_COMPRA]  WITH CHECK ADD  CONSTRAINT [fk_PRODUTOPRODUTO] FOREIGN KEY([IDPRODUTO])
REFERENCES [dbo].[CATALOGO] ([IDPRODUTO])
GO
ALTER TABLE [dbo].[PRODUTO_COMPRA] CHECK CONSTRAINT [fk_PRODUTOPRODUTO]
GO
ALTER TABLE [dbo].[PRODUTO_DEVOLUCAO]  WITH CHECK ADD  CONSTRAINT [fk_PRODEVPROD] FOREIGN KEY([IDPRODUTO])
REFERENCES [dbo].[CATALOGO] ([IDPRODUTO])
GO
ALTER TABLE [dbo].[PRODUTO_DEVOLUCAO] CHECK CONSTRAINT [fk_PRODEVPROD]
GO
ALTER TABLE [dbo].[PRODUTO_DEVOLUCAO]  WITH CHECK ADD  CONSTRAINT [fk_PRODUTODEVOLUCAO] FOREIGN KEY([IDDEVOLUCAO])
REFERENCES [dbo].[DEVOLUCAO] ([IDDEVOLUCAO])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRODUTO_DEVOLUCAO] CHECK CONSTRAINT [fk_PRODUTODEVOLUCAO]
GO
ALTER TABLE [dbo].[PRODUTO_VENDA]  WITH CHECK ADD  CONSTRAINT [fk_PRODUTOCATALOGO] FOREIGN KEY([IDPRODUTO])
REFERENCES [dbo].[CATALOGO] ([IDPRODUTO])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRODUTO_VENDA] CHECK CONSTRAINT [fk_PRODUTOCATALOGO]
GO
ALTER TABLE [dbo].[PRODUTO_VENDA]  WITH CHECK ADD  CONSTRAINT [fk_PRODUTOVENDA] FOREIGN KEY([IDVENDA])
REFERENCES [dbo].[VENDA] ([IDVENDA])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRODUTO_VENDA] CHECK CONSTRAINT [fk_PRODUTOVENDA]
GO